run:
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - linters:
        - lll
      source: "^//[+]kubebuilder"
linters-settings:
  govet:
    enable:
      - fieldalignment
linters:
  disable-all: true
  enable:
    - dupl
    - copyloopvar
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
