---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: telegraf-sidecar-operator
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: telegraf-sidecar-operator
        namespace: telegraf-sidecar-operator
        path: /mutate--v1-pod
    failurePolicy: Fail
    name: telegraf.mickey.dev
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
