apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: telegraf-sidecar-operator
    app.kubernetes.io/part-of: telegraf-sidecar-operator
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: admission-webhook
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: kustomize
  name: telegraf-sidecar-operator
  namespace: telegraf-sidecar-operator
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: telegraf-sidecar-operator
