apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: telegraf-sidecar-operator
    app.kubernetes.io/part-of: telegraf-sidecar-operator
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: kustomize
  name: telegraf-sidecar-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: telegraf-sidecar-operator
subjects:
  - kind: ServiceAccount
    name: telegraf-sidecar-operator
    namespace: telegraf-sidecar-operator
