apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: telegraf-sidecar-operator
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: telegraf-sidecar-operator
    app.kubernetes.io/managed-by: kustomize
  name: telegraf-sidecar-operator
  namespace: telegraf-sidecar-operator
