apiVersion: v1
kind: Secret
metadata:
  name: telegraf-classes
  namespace: telegraf-sidecar-operator
  labels:
    app: telegraf-sidecar-operator
type: Opaque
data:
  default: W2FnZW50XQogIGludGVydmFsID0gIjEwcyIKICByb3VuZF9pbnRlcnZhbCA9IHRydWUKICBtZXRyaWNfYmF0Y2hfc2l6ZSA9IDEwMDAKICBtZXRyaWNfYnVmZmVyX2xpbWl0ID0gMTAwMDAKICBjb2xsZWN0aW9uX2ppdHRlciA9ICIwcyIKICBmbHVzaF9pbnRlcnZhbCA9ICIxMHMiCiAgZmx1c2hfaml0dGVyID0gIjNzIgogIGRlYnVnID0gZmFsc2UKICBxdWlldCA9IGZhbHNlCiAgbG9nZmlsZSA9ICIiCiAgaG9zdG5hbWUgPSAiJE5PREVOQU1FIgpbW291dHB1dHMuZmlsZV1dCiAgZmlsZXMgPSBbInN0ZG91dCJdCltnbG9iYWxfdGFnc10KICBwb2RfbmFtZSA9ICIkSE9TVE5BTUUiCiAgbm9kZW5hbWUgPSAiJE5PREVOQU1FIgogIG5hbWVzcGFjZSA9ICIkTkFNRVNQQUNFIgogIHR5cGUgPSAiYXBwIg==
