{{- $caPrefix := printf "%s-ca" .Release.Name }}
{{- $ca := genCA $caPrefix 3650 }}
{{- $cn := (include "_helpers.fullname" .) }}
{{- $altNames := list ( printf "%s.%s" (include "_helpers.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "_helpers.fullname" .) .Release.Namespace ) }}
{{- $cert := genSignedCert $cn nil $altNames 3650 $ca }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "_helpers.fullname" . }}-tls
  labels:
    {{- include "_helpers.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: webhook
    {{- include "_helpers.labels" . | nindent 4 }}
  name: {{ include "_helpers.fullname" . }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "_helpers.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate--v1-pod
      caBundle: {{ $ca.Cert | b64enc }}
    failurePolicy: Ignore
    name: telegraf.mickey.dev
    {{- with .Values.operator.mutatingWebhook.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
