apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "_helpers.labels" . | nindent 4 }}
  name: {{ include "_helpers.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "_helpers.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "_helpers.fullname" . }}
    namespace: {{ .Release.Namespace }}