{{- if .Values.operator.classes.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.operator.classes.secretName }}
  labels:
    {{ include "_helpers.labels" . }}
stringData: {{ .Values.operator.classes.data | toYaml | nindent 2 }}
{{- end }}