apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "_helpers.fullname" . }}
  labels:
    {{- include "_helpers.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
