name: Main
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: "1.22"

      - name: Test
        run: make test

      - name: Create test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
        if: always()

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: "1.22"

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: "--timeout 5m"

  build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.io

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Publish Multiarch
        run: make publish-multiarch

  trivy-codescan:
    needs: build
    uses: ./.github/workflows/template-trivy-scan.yaml
    with:
      runs-on: "ubuntu-latest"
      scan-type: "fs"
      format: "sarif"
      exit-code: 0
      publish: true

  trivy-scan-image:
    needs: build
    uses: ./.github/workflows/template-trivy-scan.yaml
    with:
      runs-on: "ubuntu-latest"
      scan-type: "image"
      format: "sarif"
      image-ref: docker.io/jmickey/telegraf-sidecar-operator:main
      exit-code: 0
      publish: true
